//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetTime
    {
        public string UserId { get; set; }
        public int TicketId { get; set; }
        public Nullable<int> MasterTicketId { get; set; }
        public string PocketPcId { get; set; }
        public string ModuleCode { get; set; }
        public int TrkIndexNumber { get; set; }
        public string KCode1 { get; set; }
        public string KCode2 { get; set; }
        public string KCode3 { get; set; }
        public string KCode4 { get; set; }
        public Nullable<float> KValue { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<System.DateTime> EndBillTime { get; set; }
        public int Duration { get; set; }
        public Nullable<int> DurationBill { get; set; }
        public int Inactive { get; set; }
        public int Break { get; set; }
        public string ChargeCode { get; set; }
        public string Instructions { get; set; }
        public string Notes { get; set; }
        public string PostResults { get; set; }
        public string TicketStatus { get; set; }
        public Nullable<bool> TicketLocked { get; set; }
        public Nullable<decimal> TicketRate { get; set; }
        public string TicketRateType { get; set; }
        public Nullable<decimal> TicketTotalCharged { get; set; }
        public Nullable<bool> Void { get; set; }
        public Nullable<int> BudgetTime1 { get; set; }
        public string WorkOrderNumber { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public Nullable<float> PercentBudgetTime { get; set; }
        public Nullable<float> PercentBudgetAmount { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string TestTracktive { get; set; }
        public Nullable<int> UserNumber { get; set; }
    }
}
