//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public string BusCity { get; set; }
        public string BusCountry { get; set; }
        public string BusinessTelephone1 { get; set; }
        public string BusinessTelephone1Ext { get; set; }
        public string BusinessTelephone2 { get; set; }
        public string BusinessTelephone2Ext { get; set; }
        public string BusinessTelephone3 { get; set; }
        public string BusinessTelephone3Ext { get; set; }
        public string BusPostalZipCode { get; set; }
        public string BusProvinceState { get; set; }
        public string BusStreet1 { get; set; }
        public string BusStreet2 { get; set; }
        public string BusStreet3 { get; set; }
        public string Company { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string EmailAddress1 { get; set; }
        public string EmailAddress2 { get; set; }
        public string EmailAddress3 { get; set; }
        public string FaceBook { get; set; }
        public string FileAs { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> FkContactGroupId { get; set; }
        public string GoogleMessenger { get; set; }
        public string HomeCity { get; set; }
        public string HomeCountry { get; set; }
        public string HomePostalZipCode { get; set; }
        public string HomeProvinceState { get; set; }
        public string HomeStreet1 { get; set; }
        public string HomeStreet2 { get; set; }
        public string HomeStreet3 { get; set; }
        public string HomeTelephone1 { get; set; }
        public string HomeTelephone2 { get; set; }
        public byte[] ImageInByte { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public string JobTitle { get; set; }
        public string LastName { get; set; }
        public string LinkedIn { get; set; }
        public string MeetingMessenger { get; set; }
        public string MessengerOther { get; set; }
        public string MiddleName { get; set; }
        public string MobileTelephone1 { get; set; }
        public string MobileTelephone2 { get; set; }
        public string MSNMessenger { get; set; }
        public string Notes { get; set; }
        public byte[] NotesByte { get; set; }
        public string OtherCity { get; set; }
        public string OtherCountry { get; set; }
        public string OtherPostalZipCode { get; set; }
        public string OtherProvinceState { get; set; }
        public string OtherStreet1 { get; set; }
        public string OtherStreet2 { get; set; }
        public string OtherStreet3 { get; set; }
        public string OtherTelephone { get; set; }
        public long PkContactId { get; set; }
        public string Skype1 { get; set; }
        public string Skype2 { get; set; }
        public string SocialSpare1 { get; set; }
        public string SocialSpare2 { get; set; }
        public string SocialSpare3 { get; set; }
        public string SocialSpare4 { get; set; }
        public string SocialSpare5 { get; set; }
        public string Title { get; set; }
        public string Twitter { get; set; }
        public string VacationTelephone1 { get; set; }
        public string VacationTelephone2 { get; set; }
        public string VideoConferencing { get; set; }
        public string WebConferencing { get; set; }
        public string www1 { get; set; }
        public string www2 { get; set; }
        public string www3 { get; set; }
        public string YahooMessenger { get; set; }
        public string Fax { get; set; }
    }
}
