//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITC_Discipline
    {
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public string UserId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryGroupCode { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryLink { get; set; }
        public Nullable<int> CategoryLinkNumber { get; set; }
        public Nullable<short> CategoryOrder { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public string Department { get; set; }
        public string Contact { get; set; }
        public string CompanyPhone { get; set; }
        public string MobilePhone { get; set; }
        public string Fax { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string ProvState { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<float> BudgetHours { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public Nullable<System.DateTime> ClientSince { get; set; }
        public Nullable<bool> IsDefaultRate { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<float> CategoryBudgetHours { get; set; }
        public Nullable<decimal> CategoryBudgetAmount { get; set; }
        public Nullable<float> CategoryActualHours { get; set; }
        public Nullable<decimal> CategoryActualAmount { get; set; }
        public string DefaultTicketType { get; set; }
        public string CategoryPONumber { get; set; }
        public string CategoryInvoiceNumber { get; set; }
        public string CategoryGLAccount { get; set; }
        public string CategoryWorkOrderNumber { get; set; }
        public Nullable<float> CategoryBillableHours { get; set; }
        public Nullable<decimal> CategoryBillableAmount { get; set; }
        public Nullable<decimal> CategoryWageCost { get; set; }
        public Nullable<int> UserNumber { get; set; }
        public Nullable<int> DefaultTicketTypeNumber { get; set; }
        public Nullable<int> UserGroupNumber { get; set; }
        public Nullable<int> CategoryNumber { get; set; }
        public string DisciplineType { get; set; }
        public string DisciplineName { get; set; }
        public byte[] CategoryInstructions { get; set; }
        public byte[] Notes { get; set; }
        public string InstructionsText { get; set; }
        public string NotesText { get; set; }
    }
}
