//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITC_Project
    {
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public string UserId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryGroupCode { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryLink { get; set; }
        public Nullable<int> CategoryLinkNumber { get; set; }
        public Nullable<short> CategoryOrder { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public Nullable<float> CategoryBudgetHours { get; set; }
        public Nullable<decimal> CategoryBudgetAmount { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> RequiredByDate { get; set; }
        public string PONumber { get; set; }
        public string Quote { get; set; }
        public string SignOffBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public Nullable<bool> IsDefaultRate { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<float> CategoryActualHours { get; set; }
        public Nullable<decimal> CategoryActualAmount { get; set; }
        public string DefaultTicketType { get; set; }
        public string CategoryPONumber { get; set; }
        public string CategoryInvoiceNumber { get; set; }
        public string CategoryWorkOrderNumber { get; set; }
        public Nullable<float> CategoryBillableHours { get; set; }
        public Nullable<decimal> CategoryBillableAmount { get; set; }
        public Nullable<decimal> CategoryWageCost { get; set; }
        public string ProjectManagerTel { get; set; }
        public string ProjectManagerCell { get; set; }
        public string ProjectManagerEmail { get; set; }
        public string ProjectManager { get; set; }
        public string ProjectClientContact { get; set; }
        public Nullable<int> CategoryNumber { get; set; }
        public Nullable<int> UserNumber { get; set; }
        public Nullable<int> UserGroupNumber { get; set; }
        public Nullable<int> DefaultTicketTypeNumber { get; set; }
        public string ProjectAddress1 { get; set; }
        public string ProjectAddress2 { get; set; }
        public string ProjectCity { get; set; }
        public string ProjectProvState { get; set; }
        public string ProjectSitePhone { get; set; }
        public string ClientPM { get; set; }
        public string ClientPMCellPhone { get; set; }
        public string ClientPMEmail { get; set; }
        public string ClientPMTel { get; set; }
        public string DefaultFeeType { get; set; }
        public string DefaultFeeSchedule { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public byte[] Notes { get; set; }
        public byte[] categoryInstructions { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Currency { get; set; }
        public Nullable<int> PercentComplete { get; set; }
        public Nullable<int> Discipline { get; set; }
        public Nullable<decimal> CostToDate { get; set; }
        public string NotesText { get; set; }
        public string InstructionsText { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<short> BudgetHours { get; set; }
        public Nullable<decimal> BudgetBilling { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<bool> OnHold { get; set; }
        public Nullable<double> AlertOnBudget { get; set; }
        public Nullable<double> ALertOnHours { get; set; }
        public string ListIdX { get; set; }
        public string EditSequenceX { get; set; }
        public Nullable<int> GLIncomeAccountId { get; set; }
        public Nullable<int> GLExpenseAccountId { get; set; }
        public string JobType { get; set; }
    }
}
