//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITC_TicketType
    {
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public string UserId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryGroupCode { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryLink { get; set; }
        public Nullable<short> CategoryOrder { get; set; }
        public string CategoryInstructions { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<float> BudgetHours { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public Nullable<bool> IsDefaultRate { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<int> CategoryLinkNumber { get; set; }
        public Nullable<float> CategoryBudgetHours { get; set; }
        public Nullable<decimal> CategoryBudgetAmount { get; set; }
        public Nullable<float> CategoryActualHours { get; set; }
        public Nullable<decimal> CategoryActualAmount { get; set; }
        public string DefaultTicketType { get; set; }
        public string CategoryPONUmber { get; set; }
        public string CategoryInvoiceNumber { get; set; }
        public string CategoryGLAccount { get; set; }
        public string CategoryWorkOrderNumber { get; set; }
        public Nullable<bool> TaskActSetDft { get; set; }
        public Nullable<float> CategoryBillableHours { get; set; }
        public Nullable<decimal> CategoryBillableAmount { get; set; }
        public Nullable<decimal> CategoryWageCost { get; set; }
        public Nullable<int> CategoryNumber { get; set; }
        public Nullable<int> UserNumber { get; set; }
    }
}
