//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollItem
    {
        public long PkPayrollItemId { get; set; }
        public string WageType { get; set; }
        public string ItemName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> GLExpenseAccountId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ListId { get; set; }
        public string EditSequence { get; set; }
    }
}
