//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBAccountDetail
    {
        public long AccountId { get; set; }
        public string Account { get; set; }
        public string AccountName { get; set; }
        public string AccountType { get; set; }
        public string AccountNumber { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Description { get; set; }
        public string ListId { get; set; }
        public string EditSequence { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> RevisedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
    }
}
