//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBBill
    {
        public long PkBillId { get; set; }
        public Nullable<long> FkSyncId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string QBBillTxnId { get; set; }
        public string QBBillEditSequence { get; set; }
        public string BillType { get; set; }
        public string QBTxnDate { get; set; }
        public string QBRefNumber { get; set; }
        public Nullable<long> FkVendorId { get; set; }
        public string QBVendor_ListId { get; set; }
        public Nullable<bool> IsSynced { get; set; }
        public Nullable<long> FkApprovedUserId { get; set; }
    }
}
