//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBGLAccountNumber
    {
        public long QBGLAccountId { get; set; }
        public string ItemType { get; set; }
        public string GLExpense_ { get; set; }
        public string GLPurchase_ { get; set; }
        public string GLIncome_ { get; set; }
        public string GLAsset_ { get; set; }
        public Nullable<int> GLExpenseAccountId { get; set; }
        public Nullable<int> GLPurchaseAccountId { get; set; }
        public Nullable<int> GLIncomeAccountId { get; set; }
        public Nullable<int> GLAssetAccountId { get; set; }
    }
}
