//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportProjectLogo
    {
        public Nullable<int> ReportObjectNumber { get; set; }
        public Nullable<int> LogoIndexNumber { get; set; }
        public string RangeName { get; set; }
        public int TrkIndexNumber { get; set; }
        public string LogoName { get; set; }
        public string LogoDescription { get; set; }
        public string ReportTitle { get; set; }
        public Nullable<bool> ReportPeriod { get; set; }
    }
}
