//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTime
    {
        public string Reference { get; set; }
        public int TrkIndexNumber { get; set; }
        public string UserId { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<int> MasterTicketId { get; set; }
        public string PocketPcId { get; set; }
        public string ModuleCode { get; set; }
        public string KCode1 { get; set; }
        public string KCode2 { get; set; }
        public string KCode3 { get; set; }
        public string KCode4 { get; set; }
        public Nullable<float> KValue { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> EndBillTime { get; set; }
        public Nullable<long> Duration { get; set; }
        public Nullable<int> DurationBill { get; set; }
        public Nullable<int> Inactive { get; set; }
        public Nullable<int> Break { get; set; }
        public string ChargeCode { get; set; }
        public string Instructions { get; set; }
        public string Notes { get; set; }
        public string PostResults { get; set; }
        public string TicketStatus { get; set; }
        public Nullable<bool> TicketLocked { get; set; }
        public Nullable<decimal> TicketRate { get; set; }
        public string TicketRateType { get; set; }
        public Nullable<decimal> TicketTotalActual { get; set; }
        public Nullable<bool> Void { get; set; }
        public Nullable<int> BudgetTime { get; set; }
        public string WorkOrderNumber { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public Nullable<float> PercentBudgetTime { get; set; }
        public Nullable<float> PercentBudgetAmount { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string GLAccount { get; set; }
        public Nullable<decimal> TicketTotalBilled { get; set; }
        public Nullable<bool> TicketAcctBillable { get; set; }
        public Nullable<System.DateTime> TicketAcctExportDate { get; set; }
        public Nullable<System.DateTime> TicketPayrollExportDate { get; set; }
        public Nullable<decimal> TicketWageCost { get; set; }
        public string TicketAcctInvoice { get; set; }
        public Nullable<bool> TicketPayrollBillable { get; set; }
        public Nullable<int> KINumber1 { get; set; }
        public Nullable<int> KINumber2 { get; set; }
        public Nullable<int> KINumber3 { get; set; }
        public Nullable<int> KINumber4 { get; set; }
        public string TicketRateNumber { get; set; }
        public Nullable<int> TicketTypeNumber { get; set; }
        public Nullable<int> UserNumber { get; set; }
        public Nullable<int> TicketIdNumber { get; set; }
        public Nullable<float> CategoryBudgetHours { get; set; }
        public Nullable<float> CategoryBillableHours { get; set; }
        public string ProjectManager { get; set; }
        public string ProjectAddress1 { get; set; }
        public string ProjectCity { get; set; }
        public string ProjectSitePhone { get; set; }
        public string ClientPM { get; set; }
        public string ClientPMCellPhone { get; set; }
        public string ClientPMEmail { get; set; }
        public Nullable<System.DateTime> RequiredByDate { get; set; }
        public string ProjectProvState { get; set; }
        public Nullable<int> DispatchIdNumber { get; set; }
        public string CategoryPONumber { get; set; }
        public Nullable<long> NotesNumber { get; set; }
        public Nullable<long> InstructionNumber { get; set; }
        public Nullable<long> ResultNumber { get; set; }
        public Nullable<long> KINumber5 { get; set; }
        public string KCode5 { get; set; }
        public Nullable<long> TaskNumber { get; set; }
        public string ActivityMode { get; set; }
        public Nullable<int> AssignedByUser { get; set; }
        public string Currency { get; set; }
        public Nullable<long> ReferenceNumber { get; set; }
        public string Discipline { get; set; }
        public string ProjectAddress2 { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<bool> Billable { get; set; }
        public Nullable<bool> SRED { get; set; }
        public string TxnID { get; set; }
        public string EditSequence { get; set; }
        public Nullable<bool> IsQBSYNC { get; set; }
        public string EstimateTxnId { get; set; }
        public string EstimateEditSequence { get; set; }
        public string BillTxnId { get; set; }
        public string BillEditSequence { get; set; }
        public Nullable<long> QBSYNCId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
