//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketReport
    {
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public string UserId { get; set; }
        public Nullable<short> ReportOrder { get; set; }
        public string GroupCode { get; set; }
        public string ReportTitle { get; set; }
        public string Reference { get; set; }
        public string ReportCode { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> ReportDistinct { get; set; }
        public string ReportFields { get; set; }
        public string ReportTables { get; set; }
        public string ReportCondition { get; set; }
        public string ReportGroup { get; set; }
        public string ReportSort { get; set; }
        public string ReportCaption { get; set; }
        public string ReportFormatField { get; set; }
        public Nullable<bool> IncludeDateFilter { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<bool> IncludeUserFilter { get; set; }
        public Nullable<bool> IncludeCategoryFilter { get; set; }
        public string ReportSql { get; set; }
        public Nullable<short> SubTotal { get; set; }
        public Nullable<bool> ReportTotal { get; set; }
        public Nullable<short> SecureLevel { get; set; }
        public Nullable<bool> ExcelWordWrap { get; set; }
        public Nullable<bool> ExcelAutoWidth { get; set; }
        public string ExcelTemplate { get; set; }
        public string ExcelFilename { get; set; }
        public string ReportColumnWidth { get; set; }
        public Nullable<bool> ExcelHeaderInfo { get; set; }
        public string ExcelPageFormat { get; set; }
        public Nullable<int> ExcelPageBreak { get; set; }
        public Nullable<bool> ExcelPBHeaderInfo { get; set; }
        public string ExcelReportType { get; set; }
        public Nullable<bool> ExcelGridLines { get; set; }
        public Nullable<short> ReportMajorSpacing { get; set; }
        public Nullable<short> ReportMinorSpacing { get; set; }
        public Nullable<bool> ExcelMergeCells { get; set; }
        public Nullable<bool> IncludeTicketTypeFilter { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string ReportType { get; set; }
        public Nullable<short> ExcelRowStart { get; set; }
        public Nullable<short> ExcelColStart { get; set; }
        public Nullable<bool> ExcelCompanyInfo { get; set; }
        public Nullable<bool> ExcelDoMacro { get; set; }
        public Nullable<long> ReportGroupNumber { get; set; }
        public Nullable<long> ReportNumber { get; set; }
        public Nullable<int> UserNumber { get; set; }
    }
}
