//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTask
    {
        public int TrkIndexNumber { get; set; }
        public string UserId { get; set; }
        public string ModuleCode { get; set; }
        public Nullable<int> TaskNumber { get; set; }
        public int TicketId { get; set; }
        public string Reference { get; set; }
        public string Instructions { get; set; }
        public short InitialPriority { get; set; }
        public Nullable<short> ActivePriority { get; set; }
        public string KCode1 { get; set; }
        public string KCode2 { get; set; }
        public string KCode3 { get; set; }
        public string KCode4 { get; set; }
        public Nullable<float> KValue { get; set; }
        public string ChargeCode { get; set; }
        public string DispatchId { get; set; }
        public System.DateTime DispatchTime { get; set; }
        public System.DateTime AppointmentStartTime { get; set; }
        public System.DateTime AppointmentEndTime { get; set; }
        public Nullable<int> AppointmentDuration { get; set; }
        public Nullable<bool> Void { get; set; }
        public string PONumber { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public Nullable<int> BudgetTime { get; set; }
        public string WorkOrderNumber { get; set; }
        public string Contact { get; set; }
        public string CompanyPhone { get; set; }
        public string MobilePhone { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string GLAccount { get; set; }
        public Nullable<int> KINumber1 { get; set; }
        public Nullable<int> KINumber2 { get; set; }
        public Nullable<int> KINumber3 { get; set; }
        public Nullable<int> KINumber4 { get; set; }
        public Nullable<int> TicketTypeNumber { get; set; }
        public Nullable<int> UserNumber { get; set; }
        public Nullable<int> DispatchIdNumber { get; set; }
        public string CategoryPONumber { get; set; }
        public Nullable<float> CategoryBudgetHours { get; set; }
        public Nullable<float> CategoryBillableHours { get; set; }
        public string ProjectManager { get; set; }
        public string ProjectAddress1 { get; set; }
        public string ProjectAddress2 { get; set; }
        public string ProjectCity { get; set; }
        public string ProjectSitePhone { get; set; }
        public string ClientPM { get; set; }
        public string ClientPMCellPhone { get; set; }
        public string ClientPMEmail { get; set; }
        public Nullable<System.DateTime> RequiredByDate { get; set; }
        public string ProjectProvState { get; set; }
        public string Discipline { get; set; }
        public Nullable<long> KINumber5 { get; set; }
        public string KCode5 { get; set; }
        public Nullable<long> NewTicketID { get; set; }
        public Nullable<long> NotesNumber { get; set; }
        public Nullable<long> InstructionNumber { get; set; }
        public Nullable<long> TicketNumber { get; set; }
        public Nullable<int> AssignedBy { get; set; }
        public string Currency { get; set; }
        public Nullable<long> ReferenceNumber { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<bool> Billable { get; set; }
        public Nullable<bool> SRED { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
