//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TracktiveQB_SYNCDetails
    {
        public long SYNCId { get; set; }
        public string QBConnectionStatus { get; set; }
        public string QBSessionStatus { get; set; }
        public string SYNCType { get; set; }
        public Nullable<System.DateTime> SYNCEndTime { get; set; }
        public string SYNCEndMessage { get; set; }
        public string SYNCStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<long> FkCreatedBy { get; set; }
        public string SYNCStatusMessage { get; set; }
        public Nullable<long> FkApprovedUserId { get; set; }
    }
}
