//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TracktiveQB_Response
    {
        public long ResponseId { get; set; }
        public Nullable<long> FkRequestId { get; set; }
        public string ResponseXML { get; set; }
        public string StatusCode { get; set; }
        public string StatusSeverity { get; set; }
        public string StatusMessage { get; set; }
        public Nullable<bool> IsSYNC { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<long> FkCreatedBy { get; set; }
    }
}
