//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TracktiveDocReferenceLink
    {
        public string TableName { get; set; }
        public Nullable<long> TableINumber { get; set; }
        public Nullable<long> ReferenceINumber { get; set; }
        public long ReferenceLinkNumber { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
