//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TracktiveQB_TransactionLog
    {
        public long TransactionLogId { get; set; }
        public Nullable<long> FkRequestId { get; set; }
        public string TrkTableName { get; set; }
        public string TrkListName { get; set; }
        public string QBListName { get; set; }
        public Nullable<long> FkTrkRecordId { get; set; }
        public string QBListId { get; set; }
        public string RequestType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<long> FkCreatedBy { get; set; }
    }
}
