//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkAddInfo
    {
        public int AddInfoNumber { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string Screen { get; set; }
        public string CategoryName { get; set; }
        public string TableName { get; set; }
        public string ConditionField { get; set; }
        public string PrimaryTableName { get; set; }
        public string PrimaryConditionField { get; set; }
    }
}
