//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkBatchFile
    {
        public string UserId { get; set; }
        public Nullable<short> SecureLevel { get; set; }
        public string ModuleCode { get; set; }
        public string BatchName { get; set; }
        public string BatchType { get; set; }
        public Nullable<short> BatchOrder { get; set; }
        public string BatchCommand { get; set; }
        public string BatchValues { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<int> UserNumber { get; set; }
    }
}
