//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkClientInfo
    {
        public int TrkIndexNumber { get; set; }
        public Nullable<int> CategoryNumber { get; set; }
        public Nullable<decimal> CategoryOTBillableRate { get; set; }
        public Nullable<decimal> categoryPremiumBillableRate { get; set; }
        public string GLAcct1 { get; set; }
        public string GLAcct2 { get; set; }
        public string GLAcct3 { get; set; }
        public string Tax1 { get; set; }
        public string Tax2 { get; set; }
        public string Tax3 { get; set; }
        public string Tax4 { get; set; }
        public string DefaultFeeType { get; set; }
        public string DefaultFeeSchedule { get; set; }
        public string CategoryLink { get; set; }
    }
}
