//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkCategoryContact
    {
        public long PkTrkCategoryContact { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long FkCategoryId { get; set; }
        public long FkContactId { get; set; }
        public int CategoryFlag { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
    }
}
