//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class trkClientContact
    {
        public int TrkIndexNumber { get; set; }
        public string NameTitle { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string JobTitle { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public string TelOffice1 { get; set; }
        public string Ext1 { get; set; }
        public string TelOffice2 { get; set; }
        public string TelSite { get; set; }
        public string Ext { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string SiteFax { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string TelHome { get; set; }
        public Nullable<int> CategoryNumber { get; set; }
        public string CategoryType { get; set; }
    }
}
