//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkDataGroup
    {
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public int TrkIndexNumber { get; set; }
        public string DataGroup { get; set; }
        public string DGName { get; set; }
        public string DGCode { get; set; }
        public Nullable<float> DGValue { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string LinkTable { get; set; }
        public string LinkField { get; set; }
        public string LinkFieldValue { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<bool> AllowEdit { get; set; }
    }
}
