//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkDetailScreenField
    {
        public string FieldGroup { get; set; }
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public Nullable<short> ColumnOrder { get; set; }
        public Nullable<bool> ColumnOrderFixed { get; set; }
        public string FieldTable { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> FieldType { get; set; }
        public string FieldCaption { get; set; }
        public Nullable<bool> FieldVisible { get; set; }
        public string FieldDescription { get; set; }
        public Nullable<bool> ColumnResizable { get; set; }
        public Nullable<bool> ColumnFrozen { get; set; }
        public Nullable<short> ColumnWidth { get; set; }
        public Nullable<bool> FieldEdit { get; set; }
        public string FieldEditObject { get; set; }
        public string FieldEditList { get; set; }
        public string FieldTranslationType { get; set; }
        public string FieldTranslationTable { get; set; }
        public string FieldTranslationFilter { get; set; }
        public string FieldTranslationCode { get; set; }
        public string FieldTranslationCaption { get; set; }
        public string FieldDisplayFormat { get; set; }
        public string FieldMultiplier { get; set; }
        public Nullable<bool> DoTotal { get; set; }
        public Nullable<bool> IsRate { get; set; }
        public Nullable<bool> Active { get; set; }
        public int FieldGroupNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string FieldCheck { get; set; }
        public string SummaryType { get; set; }
        public Nullable<int> ForegroundColour { get; set; }
        public Nullable<int> BackgroundColour { get; set; }
        public Nullable<bool> FontBold { get; set; }
        public Nullable<bool> FontUnderline { get; set; }
        public Nullable<bool> FontItalics { get; set; }
        public string Font { get; set; }
        public Nullable<int> FontSize { get; set; }
        public Nullable<int> ColumnSortMode { get; set; }
        public Nullable<short> FieldSortOrder { get; set; }
        public Nullable<int> SecureLevel { get; set; }
        public Nullable<long> UserNumber { get; set; }
        public Nullable<long> UserGroupNumber { get; set; }
        public Nullable<bool> FieldIsReference { get; set; }
        public string FieldSourceRelation { get; set; }
        public Nullable<bool> DetailEdit { get; set; }
        public Nullable<bool> DetailEnabled { get; set; }
        public string DetailName { get; set; }
        public string DetailText { get; set; }
        public Nullable<int> DetailRow { get; set; }
        public Nullable<int> DetailColumn { get; set; }
        public Nullable<int> DetailRowSpan { get; set; }
        public Nullable<int> DetailColSpan { get; set; }
        public Nullable<int> DetailGridRows { get; set; }
        public Nullable<int> DetailGridColumns { get; set; }
        public Nullable<bool> DetailIsChecked { get; set; }
        public Nullable<bool> DetailIsMultiline { get; set; }
        public Nullable<int> DetailFontSize { get; set; }
        public Nullable<bool> DetailBold { get; set; }
        public Nullable<bool> DetailItalic { get; set; }
        public Nullable<bool> DetailUnderline { get; set; }
        public string DetailForeColor { get; set; }
        public string GridFieldGroup { get; set; }
        public string GridSP { get; set; }
        public string DetailObjectType { get; set; }
        public string DetailBackColor { get; set; }
        public string DetailFontColor { get; set; }
    }
}
