//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkFilterField
    {
        public int FilterID { get; set; }
        public string FilterGroup { get; set; }
        public string FilterCaption { get; set; }
        public Nullable<int> RangeStart { get; set; }
        public Nullable<int> RangeEnd { get; set; }
        public Nullable<bool> UseRangeEnd { get; set; }
        public Nullable<int> ActionButton1 { get; set; }
        public Nullable<int> ActionButton2 { get; set; }
        public Nullable<int> EditObject { get; set; }
        public string FieldName { get; set; }
        public string FieldTable { get; set; }
        public string FieldCaption { get; set; }
        public string FieldValue { get; set; }
        public string FieldCondition { get; set; }
        public string FieldList { get; set; }
        public Nullable<int> CategoryDropMode { get; set; }
        public Nullable<int> RangeStartDefault { get; set; }
        public Nullable<int> RangeEndDefault { get; set; }
        public Nullable<int> DataThershold { get; set; }
        public Nullable<int> Event2Raise { get; set; }
        public Nullable<int> CategoryOrder { get; set; }
        public string FieldLink { get; set; }
        public Nullable<int> FilterType { get; set; }
        public Nullable<int> FilterOrder { get; set; }
        public string FilterName { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string SearchCriteria { get; set; }
        public Nullable<System.DateTime> DateStartDefault { get; set; }
        public Nullable<System.DateTime> DateEndDefault { get; set; }
        public string SearchCriteriaDefault { get; set; }
        public Nullable<long> ValuePosition { get; set; }
        public string PassInfoFieldGroup { get; set; }
        public string CategoryFeeType { get; set; }
        public string CategoryFeeSchedule { get; set; }
        public Nullable<bool> CanHold { get; set; }
        public string DefaultFee { get; set; }
        public string DefaultRate { get; set; }
    }
}
