//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkFieldList
    {
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> FieldType { get; set; }
        public Nullable<int> FieldLength { get; set; }
        public Nullable<short> FieldOrder { get; set; }
        public string Caption { get; set; }
        public string Description { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<bool> IsScreen { get; set; }
        public Nullable<bool> IsReport { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<bool> IsRate { get; set; }
        public string FieldList { get; set; }
        public string FieldFormat { get; set; }
        public string EditObject { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> DoTotal { get; set; }
        public Nullable<bool> ViewScreen { get; set; }
        public Nullable<bool> ViewReport { get; set; }
    }
}
