//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkFieldDefault
    {
        public string Screen { get; set; }
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public string Field { get; set; }
        public string FieldDefault { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<bool> IsRate { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string UserId { get; set; }
        public Nullable<int> UserNumber { get; set; }
    }
}
