//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkFieldAdjust
    {
        public string Screen { get; set; }
        public Nullable<short> ScreenOrder { get; set; }
        public Nullable<short> SortOrder { get; set; }
        public string ModuleCode { get; set; }
        public string SourceTable { get; set; }
        public string SourceVariable { get; set; }
        public string SourceCondition { get; set; }
        public string UpdateSetStatement { get; set; }
        public string UpdateCondition { get; set; }
        public string UpdateTable { get; set; }
        public string UpdateVariable { get; set; }
        public int TrkIndexNumber { get; set; }
        public string FunctionType { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
    }
}
