//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkGridScreen
    {
        public string Screen { get; set; }
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public Nullable<short> ColumnOrder { get; set; }
        public string Field { get; set; }
        public string Caption { get; set; }
        public Nullable<bool> ViewField { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Fixed { get; set; }
        public Nullable<short> ColumnWidth { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<bool> IsRate { get; set; }
        public string FieldList { get; set; }
        public string FieldFormat { get; set; }
        public string Multiplier { get; set; }
        public Nullable<int> FieldType { get; set; }
        public Nullable<bool> DoTotal { get; set; }
        public int TrkIndexNumber { get; set; }
        public string EditObject { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string FieldCheck { get; set; }
        public string SummaryType { get; set; }
        public string FieldTable { get; set; }
    }
}
