//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkImportExportTable
    {
        public string TableCaption { get; set; }
        public string TableName { get; set; }
        public Nullable<int> TableNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public int TrkIndexNumber { get; set; }
    }
}
