//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkIndTableList
    {
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> FieldType { get; set; }
        public Nullable<int> FieldLength { get; set; }
        public Nullable<short> FieldOrder { get; set; }
        public string Caption { get; set; }
        public string Description { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
    }
}
