//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkImportExportField
    {
        public string FieldCaption { get; set; }
        public string FieldName { get; set; }
        public Nullable<bool> IsMendatory { get; set; }
        public Nullable<bool> IsUnique { get; set; }
        public Nullable<int> TableNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public int TrkIndexNumber { get; set; }
    }
}
