//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkImage
    {
        public long ImageIndexNumber { get; set; }
        public byte[] ActualImage { get; set; }
        public string ImageType { get; set; }
        public string ImageSize { get; set; }
        public Nullable<long> TicketId { get; set; }
    }
}
