//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkMaterial
    {
        public string UserId { get; set; }
        public string ItemGroupCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<short> ItemQuantity { get; set; }
        public Nullable<decimal> ItemCost { get; set; }
        public Nullable<decimal> ItemTax1 { get; set; }
        public Nullable<decimal> ItemTax2 { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public string ItemAccountingCode { get; set; }
        public Nullable<bool> Active { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<int> ItemGLIncomeAccountId { get; set; }
        public Nullable<bool> IsTaxable1 { get; set; }
        public Nullable<bool> IsTaxable2 { get; set; }
        public Nullable<int> ItemGroupIndexNumber { get; set; }
        public Nullable<int> UserNumber { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public byte[] ItemInstructions { get; set; }
        public byte[] ItemNotes { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> ImportFrmAcctSystem { get; set; }
        public Nullable<bool> IsTaxable3 { get; set; }
        public Nullable<bool> IsTaxable4 { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public string InstructionsText { get; set; }
        public string NotesText { get; set; }
        public string DataTable { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<System.DateTime> Modificationdate { get; set; }
        public Nullable<int> ItemGLExpenseAccountId { get; set; }
        public Nullable<int> ItemGLPurchaseAccountId { get; set; }
        public string ListId { get; set; }
        public string EditSequence { get; set; }
    }
}
