//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkNotesDetail
    {
        public int NotesIndexNumber { get; set; }
        public byte[] Memoranda { get; set; }
        public string NotesText { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<System.DateTime> TrkModificationDate { get; set; }
        public string UserId { get; set; }
        public Nullable<long> UserNumber { get; set; }
    }
}
