//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkPassInfoField
    {
        public string FieldGroup { get; set; }
        public int FieldGroupNumber { get; set; }
        public string SourceFieldTable { get; set; }
        public string SourceFieldName { get; set; }
        public Nullable<int> SourceFieldType { get; set; }
        public string SourceFieldDescription { get; set; }
        public string DestinationFieldTable { get; set; }
        public string DestinationFieldName { get; set; }
        public Nullable<int> DestinationFieldType { get; set; }
        public string DestinationFieldDescription { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<long> UserNumber { get; set; }
        public Nullable<long> UserGroupNumber { get; set; }
    }
}
