//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkQueryCondition
    {
        public string ConditionGroup { get; set; }
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public Nullable<short> ConditionOrder { get; set; }
        public Nullable<bool> ConditionOrderFixed { get; set; }
        public string FieldTable { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> FieldType { get; set; }
        public string FieldCaption { get; set; }
        public Nullable<bool> FieldEdit { get; set; }
        public string FieldEditObject { get; set; }
        public string FieldEditList { get; set; }
        public Nullable<bool> FieldIsFilter { get; set; }
        public int ConditionNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string ConditionLogic { get; set; }
        public string ConditionDataStart { get; set; }
        public string ConditionDataEnd { get; set; }
        public string ConditionCombineLogic { get; set; }
        public Nullable<int> SecureLevel { get; set; }
        public Nullable<long> UserNumber { get; set; }
        public Nullable<long> UserGroupNumber { get; set; }
        public string ConditionDataStartValue { get; set; }
        public string ConditionDataEndValue { get; set; }
        public string FieldTranslationCode { get; set; }
        public string FieldTranslationCaption { get; set; }
        public string FieldTranslationType { get; set; }
        public string FieldTranslationTable { get; set; }
        public string FieldTranslationScope { get; set; }
        public Nullable<bool> SelectDBRow { get; set; }
        public Nullable<int> PriorityOrder { get; set; }
    }
}
