//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkReportFieldGroupDef
    {
        public string FieldGroup { get; set; }
        public string Title { get; set; }
        public Nullable<int> TableRelationNumber { get; set; }
        public Nullable<int> SecureLevel { get; set; }
        public Nullable<long> UserNumber { get; set; }
        public Nullable<long> UserGroupNumber { get; set; }
        public Nullable<long> ReportObjectNumber { get; set; }
        public int FieldGroupDefNumber { get; set; }
        public Nullable<bool> UseExcelTemplate { get; set; }
        public Nullable<bool> UseWordTemplate { get; set; }
        public Nullable<bool> UseHtmlTemplate { get; set; }
        public string WordTemplateFilename { get; set; }
        public string ExcelTemplateFilename { get; set; }
        public string HtmlTemplateFilename { get; set; }
        public string ReportObjectType { get; set; }
        public string ReportDataTag { get; set; }
        public Nullable<short> SubTotal { get; set; }
        public Nullable<bool> ReportTotal { get; set; }
        public Nullable<bool> ExcelDoMacro { get; set; }
        public string Reference { get; set; }
        public Nullable<bool> WordDoMacro { get; set; }
        public Nullable<bool> HtmlDoMacro { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string ReportObjectRangeName { get; set; }
        public string ReportObjectSP { get; set; }
        public Nullable<int> ReportPage { get; set; }
        public string ReportTable { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<int> ReportFieldGroupNumber { get; set; }
        public Nullable<bool> IsReportFieldGroupDef { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
