//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkReportFieldList
    {
        public string Table { get; set; }
        public Nullable<short> FieldOrder { get; set; }
        public string Field { get; set; }
        public string Caption { get; set; }
        public Nullable<int> FieldType { get; set; }
        public Nullable<int> FieldSize { get; set; }
        public string FieldList { get; set; }
        public string Description { get; set; }
        public Nullable<bool> ViewField { get; set; }
        public Nullable<bool> IsRate { get; set; }
        public Nullable<bool> Active { get; set; }
        public string FieldFormat { get; set; }
        public string Multiplier { get; set; }
        public Nullable<bool> DoTotal { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string EditObject { get; set; }
    }
}
