//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkReportTemplateRange
    {
        public Nullable<int> ReportTemplateNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string ReportObjectRangeName { get; set; }
        public int TrkIndexNumber { get; set; }
    }
}
