//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkRefCurrency
    {
        public int TrkIndexNumber { get; set; }
        public string CurrencyName { get; set; }
        public string Currency { get; set; }
        public string Country { get; set; }
        public Nullable<int> NumericCode { get; set; }
        public Nullable<int> MinorCode { get; set; }
        public string CultureName { get; set; }
    }
}
