//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkReportObject
    {
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public Nullable<long> UserNumber { get; set; }
        public Nullable<long> UserGroupNumber { get; set; }
        public Nullable<short> ReportOrder { get; set; }
        public string ReportGroup { get; set; }
        public string ReportTitle { get; set; }
        public string ReportTitleShort { get; set; }
        public Nullable<int> SecureLevel { get; set; }
        public string Reference { get; set; }
        public string Notes { get; set; }
        public Nullable<int> IncludeFilters { get; set; }
        public Nullable<int> FieldGroupDefNumber { get; set; }
        public Nullable<bool> UseHeaderLeftLogo { get; set; }
        public Nullable<bool> UseFooterLeftLogo { get; set; }
        public Nullable<bool> UseFooterCenterLogo { get; set; }
        public string LogoHLFilename { get; set; }
        public string LogoFLFilename { get; set; }
        public string LogoFCFilename { get; set; }
        public Nullable<bool> UseCompanyName { get; set; }
        public Nullable<bool> UseCompanyAddress { get; set; }
        public Nullable<bool> UseTitle { get; set; }
        public Nullable<bool> UseReportTitle { get; set; }
        public Nullable<bool> UseSubTitle { get; set; }
        public Nullable<bool> UseTitleDate { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public Nullable<int> UseFilters { get; set; }
        public string BodyBeforeTable { get; set; }
        public string BodyAfterTable { get; set; }
        public Nullable<bool> UseColumnWrapText { get; set; }
        public Nullable<bool> UseAutoColumnWidth { get; set; }
        public Nullable<bool> UseFooterRightDate { get; set; }
        public Nullable<bool> UseFooterCenterDate { get; set; }
        public Nullable<bool> UseFooterRightPage { get; set; }
        public Nullable<bool> UseFooterCenterPage { get; set; }
        public Nullable<bool> UseFooterRightOfPages { get; set; }
        public Nullable<bool> UseFooterCenterOfPages { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public int ReportObjectNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string ConditionGroup { get; set; }
        public Nullable<int> ReportTemplateNumber { get; set; }
        public int TrkIndexNumber { get; set; }
        public string ReportTemplateName { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<bool> DoMacro { get; set; }
        public string ReportOrientation { get; set; }
        public string ReportPageSize { get; set; }
        public Nullable<int> Zoom { get; set; }
    }
}
