//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkRefSettingsCountry
    {
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
        public string CountryPhoneFormating { get; set; }
        public string CountryPostalCodeFormating { get; set; }
        public string CountryMobileFormating { get; set; }
        public string CountrySocialLabel { get; set; }
        public string CountrySocialFormating { get; set; }
        public long TrkIndexNumber { get; set; }
        public string CountryFaxFormating { get; set; }
        public string AddressFormating { get; set; }
        public Nullable<int> DefaultOrder { get; set; }
    }
}
