//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkRefSettingState
    {
        public int TrkIndexNumber { get; set; }
        public string Country { get; set; }
        public string CountryCode { get; set; }
        public string CountryISO2 { get; set; }
        public string State { get; set; }
        public string HASC { get; set; }
        public string ISO { get; set; }
        public string PrimaryLevelName { get; set; }
    }
}
