//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkSkin
    {
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public string CategoryCaption1 { get; set; }
        public string CategoryCaption2 { get; set; }
        public string CategoryCaption3 { get; set; }
        public string CategoryCaption4 { get; set; }
        public string TitleMain { get; set; }
        public string TitleNote { get; set; }
        public string TitleTask { get; set; }
        public string TitleTicketDetails { get; set; }
        public string TitleTicketSummary { get; set; }
        public string TitleExpenseSummary { get; set; }
        public string TitleToDoList { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
    }
}
