//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkSettingsComputer
    {
        public string VariableName { get; set; }
        public Nullable<int> VariableType { get; set; }
        public string VariableValue { get; set; }
        public string VariableDefault { get; set; }
        public string ComputerName { get; set; }
        public string ModuleCode { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
    }
}
