//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkSysField
    {
        public string ModuleCode { get; set; }
        public int FieldNumber { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public Nullable<long> FieldTypeSQL { get; set; }
        public Nullable<int> FieldLength { get; set; }
        public string FieldCaption { get; set; }
        public string FieldDescription { get; set; }
        public Nullable<bool> FieldEdit { get; set; }
        public string FieldEditObject { get; set; }
        public string FieldEditList { get; set; }
        public string FieldTranslationType { get; set; }
        public string FieldTranslationCode { get; set; }
        public string FieldTranslationCaption { get; set; }
        public string FieldDisplayFormat { get; set; }
        public string FieldTranslationNumber { get; set; }
        public string FieldTranslationTable { get; set; }
        public string FieldDataFormat { get; set; }
        public string FieldMultiplier { get; set; }
        public Nullable<bool> DoTotal { get; set; }
        public Nullable<bool> IsRate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<int> ForegroundColour { get; set; }
        public Nullable<int> BackgroundColour { get; set; }
        public Nullable<bool> FontBold { get; set; }
        public Nullable<bool> FontUnderline { get; set; }
        public Nullable<bool> FontItalics { get; set; }
        public string Font { get; set; }
        public Nullable<bool> FieldAllowNulls { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<bool> FieldVisible { get; set; }
        public Nullable<bool> IsAutoFill { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<bool> IsUnique { get; set; }
    }
}
