//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkSPParameter
    {
        public int SPParameterNumber { get; set; }
        public string SPName { get; set; }
        public Nullable<int> SPPOrder { get; set; }
        public string SPPField { get; set; }
        public Nullable<int> SPPdbType { get; set; }
        public string SPPSQLDBType { get; set; }
        public string SPPDirection { get; set; }
        public Nullable<int> SPPSize { get; set; }
        public string SPPValueField { get; set; }
        public Nullable<int> SPPValuePosition { get; set; }
        public Nullable<System.DateTime> SPPCreationDate { get; set; }
    }
}
