//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkSettingsMobile
    {
        public string MobileDeviceID { get; set; }
        public Nullable<long> DaysViwed { get; set; }
        public Nullable<long> LicenseCode { get; set; }
        public long TrkIndexNumber { get; set; }
    }
}
