//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkScreenObject
    {
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public string Screen { get; set; }
        public string Screen2 { get; set; }
        public string ScreenObject { get; set; }
        public string ScreenCaption { get; set; }
        public string Description { get; set; }
        public Nullable<bool> ScreenObjectEdit { get; set; }
        public int ScreenObjectNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string FilterGroup { get; set; }
        public string Operation { get; set; }
        public string StoredProcedure { get; set; }
        public Nullable<bool> HasFieldGroup { get; set; }
        public string dsTableName { get; set; }
    }
}
