//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkScreenFieldGroupDef
    {
        public string FieldGroup { get; set; }
        public string FieldGroupCaption { get; set; }
        public Nullable<int> TableRelationNumber { get; set; }
        public Nullable<int> SecureLevel { get; set; }
        public Nullable<long> UserNumber { get; set; }
        public Nullable<long> UserGroupNumber { get; set; }
        public Nullable<long> ScreenObjectNumber { get; set; }
        public int FieldGroupDefNumber { get; set; }
        public Nullable<bool> HasRate { get; set; }
        public Nullable<bool> HasTotals { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string DetailFieldGroup1 { get; set; }
        public string DetailSP1 { get; set; }
        public string DetailFieldGroup2 { get; set; }
        public string DetailSP2 { get; set; }
        public string DetailFieldGroup3 { get; set; }
        public string DetailSP3 { get; set; }
    }
}
