//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkSettingsUser
    {
        public string VariableName { get; set; }
        public Nullable<int> VariableType { get; set; }
        public string VariableValue { get; set; }
        public string VariableDefault { get; set; }
        public string UserId { get; set; }
        public string ModuleCode { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<int> UserNumber { get; set; }
        public string DisplayMode { get; set; }
        public string DisplayScreen { get; set; }
        public string ColumnWidth { get; set; }
        public Nullable<int> ColumnOrder { get; set; }
        public Nullable<int> ColumnVisible { get; set; }
        public Nullable<byte> ColumnSortOrder { get; set; }
        public string ColumnSortOrderType { get; set; }
    }
}
