//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkSearch
    {
        public string UserId { get; set; }
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public string SearchType { get; set; }
        public string SearchMode { get; set; }
        public string SearchCaption { get; set; }
        public Nullable<short> SearchOrder { get; set; }
        public string SearchField { get; set; }
        public string SearchInformationCaption { get; set; }
        public string DataFields { get; set; }
        public string DataScreenObjects { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public int SearchId { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string DataTable { get; set; }
        public Nullable<int> ItemGroupIndexNumber { get; set; }
        public Nullable<int> UserNumber { get; set; }
    }
}
