//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkTableDef
    {
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public int TableNumber { get; set; }
        public string TableName { get; set; }
        public string TableSupport { get; set; }
        public Nullable<int> TableSupportNumber { get; set; }
        public Nullable<long> JoinTableNumber { get; set; }
        public string LinkType { get; set; }
        public string LinkName { get; set; }
        public Nullable<short> LinkOrder { get; set; }
        public Nullable<int> LinkMode { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<long> ExportGroup { get; set; }
        public string TableDescription { get; set; }
    }
}
