//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkTableRelation
    {
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public string TableRelationName { get; set; }
        public string TableRelationGroup { get; set; }
        public string TableRelationDescription { get; set; }
        public string TableRelationSQL { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public int TableRelationNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<bool> UseDesigner { get; set; }
    }
}
