//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkTableLink
    {
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public string LinkType { get; set; }
        public string LinkName { get; set; }
        public Nullable<short> LinkOrder { get; set; }
        public string LinkTable { get; set; }
        public string LinkSupportTable { get; set; }
        public string LinkScreen { get; set; }
        public string LinkScreenDetail { get; set; }
        public string SelectDisplayDefault { get; set; }
        public string CategoryField { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryValue { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string ReportType { get; set; }
        public string JoinTable { get; set; }
        public string JoinField1 { get; set; }
        public string JoinField2 { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<int> LinkMode { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
    }
}
