//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkTransferLine
    {
        public string TransferName { get; set; }
        public string LineIdentifier { get; set; }
        public Nullable<short> FieldOrder { get; set; }
        public string FieldQualifier { get; set; }
        public string SourceType { get; set; }
        public string SourceTable { get; set; }
        public string SourceField { get; set; }
        public Nullable<int> SourceFieldType { get; set; }
        public string SourceFieldOperation { get; set; }
        public string DestinationTable { get; set; }
        public string DestinationField { get; set; }
        public string DataValue { get; set; }
        public Nullable<short> DataStartColumn { get; set; }
        public Nullable<short> DataLength { get; set; }
        public Nullable<int> DataType { get; set; }
        public string DataFormat { get; set; }
        public Nullable<bool> Active { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
    }
}
