//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkTableRelationDesign
    {
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public int TableRelationNumber { get; set; }
        public int TableDesignNumber { get; set; }
        public Nullable<int> RelationOrder { get; set; }
        public string RelationTable1 { get; set; }
        public string RelationField1 { get; set; }
        public string RelationAlais1 { get; set; }
        public string RelationJoin { get; set; }
        public string RelationTable2 { get; set; }
        public string RelationField2 { get; set; }
        public string RelationAlais2 { get; set; }
    }
}
