//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkTemplate
    {
        public string FileName { get; set; }
        public string FileType { get; set; }
        public byte[] FileData { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string FileSize { get; set; }
        public int ReportTemplateNumber { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<bool> IsLayoutSet { get; set; }
        public Nullable<bool> HasMacro { get; set; }
    }
}
