//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkTableJoin
    {
        public string ModuleCode { get; set; }
        public string LanguageCode { get; set; }
        public string JoinTableName { get; set; }
        public string JoinTableGroup { get; set; }
        public string JoinTableDescription { get; set; }
        public string JoinTables { get; set; }
        public string JoinTableDef { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<int> JoinTableNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public int TrkIndexNumber { get; set; }
    }
}
