//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkUserSyncScope
    {
        public string UserName { get; set; }
        public string UserID { get; set; }
        public string ScopeName { get; set; }
        public string ScopeID { get; set; }
        public string ClientID { get; set; }
        public string ProjectID { get; set; }
        public string DateRange { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<int> UserNumber { get; set; }
    }
}
