//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkUserRateSchedule
    {
        public string RateScheduleName { get; set; }
        public string UserId { get; set; }
        public string KCode1 { get; set; }
        public string KCode2 { get; set; }
        public string KCode3 { get; set; }
        public string KCode4 { get; set; }
        public string Reference { get; set; }
        public Nullable<decimal> UserRate { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<int> KINumber1 { get; set; }
        public Nullable<int> KINumber2 { get; set; }
        public Nullable<int> KINumber3 { get; set; }
        public Nullable<int> KINumber4 { get; set; }
        public Nullable<int> UserNumber { get; set; }
    }
}
