//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkUserGroup
    {
        public string UserName { get; set; }
        public string GroupName { get; set; }
        public string GroupId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<decimal> GroupRate { get; set; }
        public Nullable<int> UserGroupNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<int> GroupIndexNumber { get; set; }
        public Nullable<int> UserNumber { get; set; }
        public string UserId { get; set; }
        public int TrkIndexNumber { get; set; }
    }
}
