//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkUser
    {
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string UserId { get; set; }
        public string LanguageCode { get; set; }
        public string ModuleName { get; set; }
        public string ModuleCode { get; set; }
        public Nullable<int> CurrentTicketId { get; set; }
        public string LastSync { get; set; }
        public string PocketPcId { get; set; }
        public Nullable<short> DefaultDaysView { get; set; }
        public string DayStart { get; set; }
        public string DayFinish { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string Password { get; set; }
        public Nullable<short> SecureLevel { get; set; }
        public Nullable<bool> LoggedIn { get; set; }
        public string UserLicense { get; set; }
        public Nullable<decimal> UserWage { get; set; }
        public Nullable<decimal> UserRate { get; set; }
        public Nullable<bool> AllowPostEdit { get; set; }
        public Nullable<bool> AllowRateView { get; set; }
        public string UserComputer { get; set; }
        public Nullable<short> DispatchLevel { get; set; }
        public int TrkIndexNumber { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string UserPayrollID { get; set; }
        public string DefaultTicketRateType { get; set; }
        public Nullable<short> AcctLevel { get; set; }
        public Nullable<bool> AllowPayRollQB { get; set; }
        public string PayRollItem { get; set; }
        public Nullable<bool> AllowActivityQB { get; set; }
        public Nullable<bool> AllowIC1QB { get; set; }
        public Nullable<bool> AllowIC2QB { get; set; }
        public Nullable<bool> AllowIC3QB { get; set; }
        public long UserNumber { get; set; }
        public string UserStreet { get; set; }
        public string UserStreet2 { get; set; }
        public string UserProvState { get; set; }
        public string UserCity { get; set; }
        public string UserState { get; set; }
        public string UserCountry { get; set; }
        public string UserPhone { get; set; }
        public string UserCustom1 { get; set; }
        public string UserEmail { get; set; }
        public string UserMobile { get; set; }
        public string UserFax { get; set; }
        public string UserCustom2 { get; set; }
        public string UserExt { get; set; }
        public string UserContactName { get; set; }
        public string UserContactRelation { get; set; }
        public Nullable<System.DateTime> UserDateHired { get; set; }
        public string MiddleName { get; set; }
        public Nullable<long> UserSSN { get; set; }
        public Nullable<int> PocketPcIndexNumber { get; set; }
        public Nullable<int> DefaultFeeSchedule { get; set; }
        public Nullable<int> DefaultDiscipline { get; set; }
        public string Discipline { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> DefaultFeeType { get; set; }
        public string PostalCode { get; set; }
        public Nullable<bool> AllowIC4QB { get; set; }
        public Nullable<int> FkPayRollItemId { get; set; }
        public string UserEmail2 { get; set; }
        public string ListId { get; set; }
        public string EditSequence { get; set; }
        public Nullable<int> GLIncomeAccountId { get; set; }
        public Nullable<int> GLExpenseAccountId { get; set; }
        public Nullable<int> GLPurchaseAccountId { get; set; }
        public string UserType { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> IsEnableVendorAccount { get; set; }
        public string VendorName { get; set; }
        public string VendorListId { get; set; }
        public string VendorEditSequence { get; set; }
        public Nullable<decimal> UserOTRate { get; set; }
        public Nullable<decimal> UserOTWage { get; set; }
        public string UserAltPhone { get; set; }
        public string EmergencyContact1Name { get; set; }
        public string EmergencyContact1Relation { get; set; }
        public string EmergencyContact1Email { get; set; }
        public string EmergencyContact1AltEmail { get; set; }
        public string EmergencyContact1Phone { get; set; }
        public string EmergencyContact1AltPhone { get; set; }
        public string EmergencyContact1Mobile { get; set; }
        public string EmergencyContact2Name { get; set; }
        public string EmergencyContact2Relation { get; set; }
        public string EmergencyContact2Email { get; set; }
        public string EmergencyContact2AltEmail { get; set; }
        public string EmergencyContact2Phone { get; set; }
        public string EmergencyContact2AltPhone { get; set; }
        public string EmergencyContact2Mobile { get; set; }
        public Nullable<System.DateTime> UserDOB { get; set; }
        public Nullable<System.DateTime> UserDateReleased { get; set; }
        public string ContactDetailsNotes { get; set; }
        public string EmergContact1DetailsNotes { get; set; }
        public string EmergContact2DetailsNotes { get; set; }
    }
}
