//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrkWorkStationInfo
    {
        public long User_ { get; set; }
        public string LicenseKey { get; set; }
        public string UserName { get; set; }
        public string LicenseType { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<System.DateTime> UnstallDate { get; set; }
        public string UserMacAddress { get; set; }
        public Nullable<System.DateTime> LicenseSaveExpiredDate { get; set; }
        public Nullable<bool> IsUserActive { get; set; }
        public Nullable<System.DateTime> LastTracktiveDataCheck { get; set; }
        public Nullable<bool> IsLicenseValid { get; set; }
        public Nullable<bool> IsTracktiveReadOnly { get; set; }
        public Nullable<bool> IsInterConnected { get; set; }
    }
}
