//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class xTicketTime
    {
        public string UserId { get; set; }
        public int TicketId { get; set; }
        public Nullable<int> MasterTicketId { get; set; }
        public string PocketPcId { get; set; }
        public string ModuleCode { get; set; }
        public int SyncNumber { get; set; }
        public string KCode1 { get; set; }
        public string KCode2 { get; set; }
        public string KCode3 { get; set; }
        public string KCode4 { get; set; }
        public Nullable<float> KValue { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<System.DateTime> EndBillTime { get; set; }
        public int Duration { get; set; }
        public Nullable<int> DurationBill { get; set; }
        public int Inactive { get; set; }
        public int Break { get; set; }
        public string ChargeCode { get; set; }
        public string Instructions { get; set; }
        public string Notes { get; set; }
        public string PostResults { get; set; }
        public string TicketStatus { get; set; }
        public Nullable<bool> TicketLocked { get; set; }
        public Nullable<decimal> TicketRate { get; set; }
        public string TicketRateType { get; set; }
        public Nullable<decimal> TicketTotalCharged { get; set; }
        public Nullable<bool> Void { get; set; }
        public Nullable<int> BudgetTime { get; set; }
        public string WorkOrderNumber { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public Nullable<float> PercentBudgetTime { get; set; }
        public Nullable<float> PercentBudgetAmount { get; set; }
        public Nullable<bool> ImportIssue { get; set; }
        public Nullable<bool> ImportWarning { get; set; }
        public string UserImport { get; set; }
        public string KCode1Import { get; set; }
        public string KCode2Import { get; set; }
        public string KCode3Import { get; set; }
        public string KCode4Import { get; set; }
        public string ChargeCodeImport { get; set; }
        public string TicketRateTypeImport { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public string CategoryPONumber { get; set; }
        public Nullable<float> CategoryBudgetHours { get; set; }
        public Nullable<float> CategoryBillableHours { get; set; }
        public string ProjectManager { get; set; }
        public string ProjectAddress1 { get; set; }
        public string ProjectCity { get; set; }
        public string ProjectSitePhone { get; set; }
        public string ClientPM { get; set; }
        public string ClientPMCellPhone { get; set; }
        public string ClientPMEmail { get; set; }
        public Nullable<System.DateTime> RequiredByDate { get; set; }
        public string ProjectProvState { get; set; }
        public Nullable<int> DispatchIdNumber { get; set; }
        public Nullable<int> UserNumber { get; set; }
    }
}
