//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracktiveDataLayer.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class xTicketExpense
    {
        public string UserId { get; set; }
        public int TicketId { get; set; }
        public Nullable<short> ItemNumber { get; set; }
        public int SyncNumber { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<short> ItemQuantity { get; set; }
        public Nullable<decimal> ItemCost { get; set; }
        public Nullable<decimal> ItemTax1 { get; set; }
        public Nullable<decimal> ItemTax2 { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public string ItemNotes { get; set; }
        public Nullable<System.DateTime> ItemDate { get; set; }
        public Nullable<int> ItemBudgetTime { get; set; }
        public Nullable<decimal> ItemBudgetAmount { get; set; }
        public Nullable<float> ItemPercentBudgetTime { get; set; }
        public Nullable<float> ItemPercentBudgetAmount { get; set; }
        public Nullable<bool> ImportIssue { get; set; }
        public Nullable<bool> ImportWarning { get; set; }
        public string UserImport { get; set; }
        public Nullable<System.DateTime> TrkCreationDate { get; set; }
        public Nullable<int> UserNumber { get; set; }
        public string Account { get; set; }
    }
}
